server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8088
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  loggers:
    org.vinturo.core: INFO
    org.hibernate.SQL: ALL
  appenders:
    - type: console
