server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 8099
      bindHost: 127.0.0.1
  adminConnectors:
    - type: http
      port: 8091
swagger:
  resourcePackage: "org.vinturo.core.io.ws.rest"
logging:
  level: INFO
  loggers:
    org.vinturo.core: INFO
    org.hibernate.SQL: ALL
  appenders:
    - type: console